name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem
      placeholder: I'm frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: I'd like...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional context

