name: Run Tests

on:
  #  push:
  #    branches:
  #      - main

  workflow_call:
    inputs:
      branch:
        description: 'Branch name to run the tests on'
        required: true
        default: 'main'
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to run the tests on'
        required: true
        default: 'main'
        type: string

jobs:
  run-tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Run unit tests
        run: mvn clean test -Punit-tests

      - name: Run integration tests
        run: mvn clean verify -Pintegration-tests
        env:
          USE_EXTERNAL_OLLAMA_HOST: "true"
          OLLAMA_HOST: "http://localhost:11434"